задание 2 попытка 1(с тестами)
Vyacheslav-TKI/CircularLinkedListEX pull request #1
Opened 2024-10-19 17:13 UTC by Vyacheslav-TKI

2024-11-01 13:34 UTC, MarinaPaley requested changes

2024-11-01 13:34 UTC, MarinaPaley commented on Solver/CircularLinkedList.h
> +        * @brief ��������� �� �����.
Файл должен быть сохранен в кодировке `UTF-8`

2024-11-01 13:34 UTC, MarinaPaley commented on Solver/CircularLinkedList.h
> +        void add(T val) {
`const T& val`

2024-11-01 13:34 UTC, MarinaPaley commented on Solver/CircularLinkedList.h
> +                std::cout << "��������� ����" << std::endl;
Ваш класс **не должен зависеть** от конкретной реализации потока ввода-вывода. Подробнее о связности и проблемах избыточной зависимости можно прочитать в [статье Германа Горелкина на Medium](https://medium.com/german-gorelkin/low-coupling-high-cohesion-d36369fb1be9).
Принципы [**SOLID**](http://sergeyteplyakov.blogspot.com/2014/10/solid.html), а именно [**D** – The Dependency Inversion Principle (DIP)](http://sergeyteplyakov.blogspot.com/2014/09/the-dependency-inversion-principle.html) также описывают проблемы связности. В частности можно привести цитату:
> Другими словами, DIP должен бороться с признаками плохого дизайном, которые так классно сформулировал все тот же Роберт Мартин в своей исходной статье о принципе инверсии зависимостей в 1996м:
> 1. Дизайн является жестким (rigid), если его тяжело изменить, поскольку любое изменение влияет на слишком большое количество других частей системы.
> 2. Дизайн является хрупким (fragile), если при внесении изменений неожиданно ломаются другие части системы.
> 3. Дизайн является неподвижным (immobile), если код тяжело использовать повторно в другом приложении, поскольку его слишком сложно «выпутать» из текущего приложения.

2024-11-01 13:34 UTC, MarinaPaley commented on Solver/CircularLinkedList.h
> +                std::cout << "��������� ���" << std::endl;
Хотите, кидайте исключение...

2024-11-08 14:46 UTC, MarinaPaley requested changes

2024-11-08 14:46 UTC, MarinaPaley commented on Solver/CircularLinkedList.h
> +            return tail == nullptr;
Всю реализацию перенести после объявления класса (вниз)

2024-11-08 14:46 UTC, MarinaPaley commented on Solver/CircularLinkedList.h
> +        void print() const {
Ваш класс **не должен зависеть** от конкретной реализации потока ввода-вывода. Подробнее о связности и проблемах избыточной зависимости можно прочитать в [статье Германа Горелкина на Medium](https://medium.com/german-gorelkin/low-coupling-high-cohesion-d36369fb1be9).
Принципы [**SOLID**](http://sergeyteplyakov.blogspot.com/2014/10/solid.html), а именно [**D** – The Dependency Inversion Principle (DIP)](http://sergeyteplyakov.blogspot.com/2014/09/the-dependency-inversion-principle.html) также описывают проблемы связности. В частности можно привести цитату:
> Другими словами, DIP должен бороться с признаками плохого дизайном, которые так классно сформулировал все тот же Роберт Мартин в своей исходной статье о принципе инверсии зависимостей в 1996м:
> 1. Дизайн является жестким (rigid), если его тяжело изменить, поскольку любое изменение влияет на слишком большое количество других частей системы.
> 2. Дизайн является хрупким (fragile), если при внесении изменений неожиданно ломаются другие части системы.
> 3. Дизайн является неподвижным (immobile), если код тяжело использовать повторно в другом приложении, поскольку его слишком сложно «выпутать» из текущего приложения.

2024-11-08 14:46 UTC, MarinaPaley commented on Solver/CircularLinkedList.h
> +                return;
все в строку!

2024-11-08 14:46 UTC, MarinaPaley commented on SolverTests/SolverTests.cpp
> +        TEST_METHOD(TestIsEmptyInitially)
[`[UnitOfWork_StateUnderTest_ExpectedBehavior]`](https://osherove.com/blog/2005/4/3/naming-standards-for-unit-tests.html)
[Именование тестовых методов](https://enterprisecraftsmanship.com/posts/you-naming-tests-wrong/)

2024-11-08 14:46 UTC, MarinaPaley commented on SolverTests/SolverTests.cpp
> +            Assert::ExpectException<std::runtime_error>(func, L"ƒолжно быть выброшено исключение при получении элемента из пустого списка.");
Не перезапускали тесты?

2024-11-15 13:26 UTC, MarinaPaley requested changes
Продолжайте

2024-11-15 13:26 UTC, MarinaPaley commented on Solver/CircularLinkedList.h
> +
Добавить вставку и удаление элемента из произвольного места и метод поиска по значению.

2024-11-15 13:26 UTC, MarinaPaley commented on Solver/CircularLinkedList.h
> +        return ws;
можно в одну строку

2024-11-15 13:26 UTC, MarinaPaley commented on Solver/CircularLinkedList.h
> +            return;
не нужно

2024-11-22 12:23 UTC, MarinaPaley requested changes

2024-11-22 12:23 UTC, MarinaPaley commented on CircularLinkedListEX/main.cpp
> +    std::cout << "��������� �������� 10, 20, 30 � ������..." << std::endl;
беда с кодировкой

2024-11-22 12:23 UTC, MarinaPaley commented on Solver/CircularLinkedList.h
> +        void add(const T& val);
`Add`

2024-11-22 12:23 UTC, MarinaPaley commented on Solver/CircularLinkedList.h
> +    std::wstring CircularLinkedList<T>::CircularLinkedList() : tail(nullptr) {}
`std::wstring` -?

2024-11-22 12:23 UTC, MarinaPaley commented on Solver/CircularLinkedList.h
> +                throw std::out_of_range("Список уже обработан");
не подходит ругательство

2024-11-22 12:23 UTC, MarinaPaley commented on Solver/CircularLinkedList.h
> +
1 строка

2024-11-22 12:23 UTC, MarinaPaley commented on SolverTests/SolverTests.cpp
> +        TEST_METHOD(TestConstructor)
[`[UnitOfWork_StateUnderTest_ExpectedBehavior]`](https://osherove.com/blog/2005/4/3/naming-standards-for-unit-tests.html)
[Именование тестовых методов](https://enterprisecraftsmanship.com/posts/you-naming-tests-wrong/)

2024-11-29 13:03 UTC, MarinaPaley requested changes

2024-11-29 13:03 UTC, MarinaPaley commented on Solver/CircularLinkedList.h
> +        */
Не все параметры описаны в документации

2024-11-29 13:03 UTC, MarinaPaley commented on Solver/CircularLinkedList.h
> +        bool FindElem(const T& elem);
Скорее это `Contains`, а вот `Find` должен возвращать узел и быть в `private `месте

2024-11-29 13:03 UTC, MarinaPaley commented on Solver/CircularLinkedList.h
> +            other.size = 0;
а почему здесь не используете `swap`?

2024-11-29 13:03 UTC, MarinaPaley commented on Solver/CircularLinkedList.h
> +        }
а иначе?

2024-11-29 18:37 UTC, Vyacheslav-TKI commented on Solver/CircularLinkedList.h
> +            other.size = 0;
забыл

2024-11-29 18:46 UTC, Vyacheslav-TKI commented on Solver/CircularLinkedList.h
> +        }
Забытая реализация(

2024-12-04 13:08 UTC, MarinaPaley requested changes
Все отлично, но.. тестовый класс загружен на половину(

2024-12-04 13:08 UTC, MarinaPaley commented on Solver/CircularLinkedList.h
> +        void swap(CircularLinkedList& other) noexcept;
`Swap`

2024-12-06 15:30 UTC, MarinaPaley approved these changes

2024-12-15 18:41 UTC, merged